In [1]:
import sqlite3
import pandas as pd
import savantscraper

# Example for two years and two teams
savantscraper.database_import('baseball_savant_all',
                              (2018, 2018))

HBox(children=(IntProgress(value=0, description='Seasons', max=1, style=ProgressStyle(description_width='initi…

HBox(children=(IntProgress(value=0, description='Teams', max=30, style=ProgressStyle(description_width='initia…

In [5]:
# Connect to the database
conn = sqlite3.connect('baseball_savant_all.db')

# Query the database and load into a pandas dataframe

df = pd.read_sql_query(
    "select pitch_type, release_speed, release_pos_x, release_pos_z, pfx_x, pfx_z, stand, p_throws, "
    "plate_x, plate_z, release_pos_y, events from statcast "
    "where events in ('single', 'double', 'triple', 'home_run', 'field_out');", conn)

# Close connection when finished
conn.close()

df

,pitch_type,release_speed,release_pos_x,release_pos_z,pfx_x,pfx_z,stand,p_throws,plate_x,plate_z,release_pos_y,events
0,FF,88.8,-1.6034,6.8141,-0.6262,1.5243,R,R,-0.2405,2.7571,54.9098,field_out
1,FF,91.1,-1.5852,6.7128,-0.6568,1.5896,R,R,-0.8574,2.3210,54.9157,field_out
2,FF,91.4,-1.7490,6.0462,-0.5245,1.3205,L,R,-0.0125,1.6343,55.3970,field_out
3,SL,87.7,2.5485,5.5453,0.0175,0.6191,L,L,-1.0876,2.3354,54.6938,field_out
4,SL,86.8,2.6798,5.4260,-0.1938,0.3464,L,L,-1.3828,2.1416,54.7086,field_out
...,...,...,...,...,...,...,...,...,...,...,...,...
116186,SL,87.5,-2.2711,5.6284,1.0023,-0.2902,R,R,-0.1673,2.1864,54.6370,field_out
116187,FF,97.0,-2.2341,5.6830,-0.6981,1.3265,R,R,0.7603,3.0872,54.5405,field_out
116188,SL,86.1,-2.6957,5.6432,1.0367,-0.6954,R,R,-0.3289,2.2584,54.8862,field_out
116189,FF,99.6,-2.3304,5.6699,-0.6119,1.4534,R,R,0.2765,3.1478,54.2575,field_out
116190,SL,89.1,-2.5866,5.7797,0.6973,-0.4938,R,R,0.8492,1.0138,54.4718,field_out

In [6]:
df.to_pickle('statcast_data.pkl')